# first useful Makefile

CC=gcc

hnm: 0-main.c
	$(CC) -Wall -Werror -Wextra -pedantic 0-main.c -o hnm
	cp hnm test
	touch 0-main.c

hobjdump: 1-main.c
	$(CC) -Wall -Werror -Wextra -pedantic 1-main.c -o hobjdump
	cp hobjdump test
	touch 1-main.c
